name: Azure Web App CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
      
      # Aqui você pode adicionar etapas adicionais, como instalação de dependências,
      # compilação de código, execução de testes, etc., dependendo das necessidades do seu aplicativo.
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'seu-nome-do-web-app'  # Substitua pelo nome do seu Web App no Azure
          slot-name: 'production'  # Substitua pelo nome do slot, se necessário
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
